version: '3'

services:


    nginx:
        image: nginx:1.15
        container_name: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8001:80
        networks:
            service_network:

        depends_on:
            - service1


    service1:
        build: servicio/.
        container_name: service1
        ports:
            - '5001:5000'
        volumes:
            - '.:/backend/code'
        environment:
            - SERVNAME=201404104
        networks:
            service_network:




    database:
        image: mysql:latest
        container_name: bases-db
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 201404104
            MYSQL_DATABASE: p8-sa
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - database:/var/lib/mysql
        networks:
            db_network:


networks:

    service_network:
        driver: bridge


    db_network:
        driver: bridge


volumes:
    database: