version: '3'

services:

  esb:
    build: esb/.
    ports:
        - 8085:8085
    networks:
      service_network:


  cliente:
    build: serivicio-cliente/.
    ports:
      - 8080:8080
    networks:
      service_network:
    depends_on:
      - esb

  repartidor:
    build: servicio-repartidor/.
    ports:
      - 8082:8082
    networks:
        service_network:
    depends_on:
      - esb


  restaurante:
    build: servicio-restaruante/.
    ports:
      - 8081:8081
    networks:
      service_network:
    depends_on:
      - esb


networks:
    service_network:
        driver: bridge

    default:
      external:
        name: service_network